// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qspfcttlcutayqbzmefp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzcGZjdHRsY3V0YXlxYnptZWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTQyNjQsImV4cCI6MjA2NjE5MDI2NH0.rEnTJ9iXg1-8y5ClprrR8_F4jyXdrmwDaMpHdZN2fNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);